name: Deploy Vite App to GitHub Pages
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        env:
          VITE_API_FILM_LIST_KEY: ${{ secrets.VITE_API_FILM_LIST_KEY }}
          VITE_API_ALOHA_KEY: ${{ secrets.VITE_API_ALOHA_KEY }}
          VITE_API_HDTV_KEY: ${{ secrets.VITE_API_HDTV_KEY }}
          VITE_API_BUGALL: ${{ secrets.VITE_API_BUGALL }}
          VITE_API_VEOVEO: ${{ secrets.VITE_API_VEOVEO }}
          VITE_API_COLL: ${{ secrets.VITE_API_COLL }}
          VITE_API_VIDEOSEED: ${{ secrets.VITE_API_VIDEOSEED }}
          VITE_API_KODI: ${{ secrets.VITE_API_KODI }}
          VITE_API_FIREBASE_API_KEY: ${{ secrets.VITE_API_FIREBASE_API_KEY }}
          VITE_API_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_API_FIREBASE_AUTH_DOMAIN }}
          VITE_API_FIREBASE_PROJECT_ID: ${{ secrets.VITE_API_FIREBASE_PROJECT_ID }}
          VITE_API_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_API_FIREBASE_STORAGE_BUCKET }}
          VITE_API_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_API_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_API_FIREBASE_APP_ID='1:452296723769: ${{ secrets.VITE_API_FIREBASE_APP_ID }}
        run: npm run build
      - name: Copy index.html to dist as 404.html
        run: cp ./dist/index.html ./dist/404.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
